language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-termite' ]; then cd .. && eval "mv $currentfolder generator-termite" && cd generator-termite; fi
